/// <reference types="node" />
import { jsonSchemaToZod, type JsonSchema } from 'json-schema-to-zod'
import { type FromSchema } from 'json-schema-to-ts'
import { resolveRefs } from 'json-refs'
// scan all the schema of ./schema
// and generate types in ./src/types.ts
import fs from 'fs'
import path from 'path'

const schemaDir = path.join(process.cwd(), './schema')
const outputFile = path.join(process.cwd(), './src/types.ts')
const schemaFiles = fs.readdirSync(schemaDir).filter(file => file.endsWith('.schema.json'))
const schemas: {
    type: string;
    schema: JsonSchema;
}[] = schemaFiles.map(file => {
    const filePath = path.join(schemaDir, file)
    const schema = JSON.parse(fs.readFileSync(filePath, 'utf-8'));
    return {
        type: file.replace('.schema.json', ''),
        schema: schema
    }
})
const zodTypes = schemas.map(schema => ({ code: jsonSchemaToZod(schema.schema), type: schema.type }))
const zodTypesString = zodTypes.map(zodType => {
    return `export const ${zodType.type} = ${zodType.code};`
}).join('\n\n')
fs.writeFileSync(outputFile, `// This file is generated by generate-types.js
// Do not edit this file manually
import { z } from 'zod/v3'
${zodTypesString}
`
)