// Generated by ts-to-zod
import { z } from "zod";

export const routeSchema = z.string();

export const hostRouterConfigSchema = z.record(routeSchema);

export const matchItemSchema = z.object({
  priority: z.number(),
  template: z.string(),
  route: routeSchema,
  path: z.string(),
});

export const pathMatchRouterConfigSchema = z.array(matchItemSchema);
