/*
 Generated by typeshare 1.13.3
*/


export type Route = string;

export type HostRouterConfig = Record<string, Route>;

export interface MatchItem {
	priority: number;
	template: string;
	route: Route;
	path: string;
}

export type PathMatchRouterConfig = MatchItem[];

