apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: switchboard
resources:
  - namespace.yaml
  - kernel-configmap.yaml
  - controller-configmap.yaml
  - deployment.yaml
  - service.yaml
