apiVersion: v1
kind: Service
metadata:
  name: switchboard
  labels:
    app.kubernetes.io/name: switchboard-all-in-one
    app.kubernetes.io/component: platform
    app.kubernetes.io/part-of: switchboard.rs
    switchboard.rs/discovery: enabled
spec:
  selector:
    app.kubernetes.io/name: switchboard-all-in-one
    switchboard.rs/discovery: enabled
  ports:
    - name: grpc
      port: 8055
      targetPort: grpc
    - name: http
      port: 8056
      targetPort: http
