config = "./examples/config/config.toml"

[info]
name = "Switchboard Kernel"
id = "default"
description = "Default Switchboard Kernel Configuration"

[controller.listen.http]

[controller.discovery]
local = "./tmp/run/kernel/"

[provider.http]
plugins = ["target/release/*"]