FROM debian:bookworm-slim

RUN apt-get update && apt-get install -y ca-certificates libssl3 && rm -rf /var/lib/apt/lists/*

# 直接复制宿主机编译好的文件
COPY target/release/sbk /usr/local/bin/sbk
COPY target/release/sbc /usr/local/bin/sbc

WORKDIR /app
CMD ["sbc"]

