apiVersion: v1
kind: Service
metadata:
  name: sbc
  labels:
    app.kubernetes.io/name: sbc
    app.kubernetes.io/component: controller
    app.kubernetes.io/part-of: switchboard.rs
spec:
  selector:
    app.kubernetes.io/name: sbc
  ports:
    - name: http
      port: 8056
      targetPort: http
